AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Create credentials for a Jamf Pro API user.

Parameters:

  Username:
    Type: String
    Description: Jamf Pro API username.

  Password:
    Type: String
    Description: Jamf Pro API password.
    NoEcho: true

Resources:

  CredentialsCreator:
    Type: AWS::Serverless::Function
    Description: Create entries in Parameter Store for Jamf Pro credentials.
    Properties:
      Handler: create_credentials.lambda_handler
      Runtime: python3.6
      CodeUri: ./src/functions/create_credentials
      Environment:
        Variables:
          STACK_NAME: !Ref AWS::StackName
          USERNAME: !Ref Username
          PASSWORD: !Ref Password
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - ssm:DeleteParameter*
              - ssm:PutParameter
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/voltron/*'

  Credentials:
    Type: Custom::Credentials
    Properties:
      ServiceToken: !GetAtt CredentialsCreator.Arn
