AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Creates a webhook receiver for Jamf Pro.

Parameters:

  AccessToken:
    Type: String
    Default: ''
    Description: Optional string to secure the API using an 'access_token' query string parameter.

  WebhookUsername:
    Type: String
    Default: ''
    Description: Optional username to secure the API using basic authentication (requires 'WebhookPassword').

  WebhookPassword:
    Type: String
    Default: ''
    Description: Optional password to secure the API using basic authentication (requires 'WebhookUsername').
    NoEcho: true


Resources:

  JamfWebhookTopic:
    Type: AWS::SNS::Topic

  WebhookReceiver:
    Type: AWS::Serverless::Function
    Description: Recieves webhook events and publishes to an SNS topic.
    Properties:
      Runtime: python3.6
      Handler: webhook_receiver.lambda_handler
      CodeUri: ./src/functions/webhook_receiver
      Environment:
        Variables:
          ACCESS_TOKEN: !Ref AccessToken
          USERNAME: !Ref WebhookUsername
          PASSWORD: !Ref WebhookPassword
          WEBHOOK_TOPIC: !Ref JamfWebhookTopic
      Policies:
        Statement:
          - Effect: Allow
            Action: sns:Publish
            Resource: !Ref JamfWebhookTopic
      Events:
        Post:
          Type: Api
          Properties:
            Path: /
            Method: post

Outputs:

  JamfWebhookTopic:
    Value: !Ref JamfWebhookTopic
    Export:
      Name: !Sub '${AWS::StackName}-JamfWebhookTopic'
